name: Lighthouse CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    env:
      # Evita erro de sandbox do Chrome no CI
      LHCI_NO_SANDBOX: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.x'

      - name: Lighthouse CI (autorun)
        run: |
          npx --yes @lhci/cli@0.13.0 autorun \
            --collect.staticDistDir=. \
            --upload.target=temporary-public-storage
        # enquanto ajustamos as métricas, não quebra o job
        continue-on-error: true

      - name: Upload LHCI artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-ci
          path: ./.lighthouseci/**
